source 'https://rubygems.org'

ruby '2.4.6'

group :production do
  gem 'airbrake'
  gem 'rails_12factor'
end
gem 'xmlrpc'
gem 'asset_sync'
gem 'barby'
gem 'binding_of_caller'
gem 'byebug'
gem 'carrierwave'
gem 'cardconnect'
gem 'coffee-rails'
gem 'compass'
gem 'compass-rails'
gem 'delayed_job_active_record'
gem 'devise'
gem 'fog', '~> 1.28.0'
gem 'fog-aws'
gem 'foundation-rails', '~> 5.0'
gem 'geocoder'
gem 'geoip'
gem 'haml'
gem 'has_barcode'
gem 'jquery-ui-rails'
gem 'koala', '~> 2.0'
gem 'mailchimp-api', require: 'mailchimp'
gem 'mandrill-api'
gem 'mandrill_mailer'
gem 'monetize'
gem 'money-rails'
gem 'omniauth-facebook'
gem 'open4'
gem 'pg', '0.20.0'
gem 'prawn-rails'
gem 'rails', '~> 4.2.0'
gem 'railties', '~> 4.2.0'
gem 'rake', '~> 10.5.0'
gem 'raygun4ruby'
gem 'rmagick'
gem 'rolify'
gem 'rvm-capistrano'
gem 'sass-rails'
gem 'simple_form'
gem 'slim-rails'
gem 'state_machines', '~> 0.4.0'
gem 'state_machines-activerecord'
gem 'state_machines-audit_trail'
gem 'therubyracer'
gem 'thin'
gem 'uglifier'
gem 'unicorn'
gem 'cardconnect'

group :development do
  gem 'better_errors'
end

group :development, :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'dotenv-rails'
end

source 'https://rails-assets.org' do
  gem 'rails-assets-jquery', '~> 2.2.4'
  gem 'rails-assets-jquery-ujs'
end
